# Generated by Django 5.2 on 2025-04-23 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='consent',
            field=models.BooleanField(default=False, help_text='Я согласен на обработку моих персональных данных', verbose_name='Согласие на обработку данных'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Введите email адрес', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Введите ваше сообщение', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='patronymic',
            field=models.CharField(help_text='Введите отчество', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Введите номер телефона в формате +7 (999) 999-99-99', max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7 (999) 999-99-99'", regex='^\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(help_text='Укажите тему сообщения', max_length=200, verbose_name='Тема'),
        ),
    ]
