# Generated by Django 5.2 on 2025-04-23 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_contact_consent_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Введите номер телефона в формате +7 (9XX) XXX-XX-XX, где X - любая цифра', max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7 (9XX) XXX-XX-XX', где X - любая цифра", regex='^\\+7 \\(9\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
