# Generated by Django 5.2 on 2025-04-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(max_length=20, verbose_name='Телефон')),
                ('pain_locations', models.JSONField(blank=True, null=True, verbose_name='Локализация боли')),
                ('pain_duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Продолжительность боли')),
                ('preferred_location', models.CharField(blank=True, max_length=20, null=True, verbose_name='Предпочтительное место консультации')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Контактная заявка',
                'verbose_name_plural': 'Контактные заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
