# Generated by Django 5.2 on 2025-04-28 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_contactsubmission_patient_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='pain_duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Продолжительность боли'),
        ),
        migrations.AddField(
            model_name='contact',
            name='pain_locations',
            field=models.JSONField(blank=True, null=True, verbose_name='Локализация боли'),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Предпочтительное место'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Введите номер телефона в формате +7 (XXX) XXX-XX-XX', max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7 (XXX) XXX-XX-XX', где первая цифра кода от 1 до 9", regex='^\\+7 \\(([1-9]\\d{2})\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
