# Generated by Django 5.2 on 2025-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_remove_contact_subject_contact_pain_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='patient_type',
            field=models.CharField(choices=[('self-paying', 'Платное лечение'), ('oms', 'ОМС')], default='self-paying', max_length=20, verbose_name='Тип пациента'),
        ),
    ]
