# Generated by Django 5.2 on 2025-11-19 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_contact_patient_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='preferred_location',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='preferred_location',
        ),
        migrations.AddField(
            model_name='contact',
            name='pain_level',
            field=models.CharField(blank=True, max_length=10, verbose_name='Уровень боли'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, help_text='Укажите тему сообщения', max_length=200, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='pain_level',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Уровень боли (1-10)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Введите номер телефона в формате +7 (XXX) XXX-XX-XX. Примеры: +7 (495) 123-45-67 (Москва), +7 (812) 123-45-67 (СПб), +7 (900) 123-45-67 (мобильный)', max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7 (XXX) XXX-XX-XX', где первая цифра кода от 1 до 9", regex='^\\+7 \\(([1-9]\\d{2})\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
